package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"errors"
	"fmt"
	"strconv"

	"github.com/ZihxS/go-graphql/graph/model"
)

// User is the resolver for the user field.
func (r *meetupResolver) User(ctx context.Context, obj *model.Meetup) (*model.User, error) {
	// return r.UsersRepo.GetUserByID(obj.UserID) // without data loader
	return getUserLoader(ctx).Load(fmt.Sprint(obj.UserID))
}

// CreateMeetup is the resolver for the createMeetup field.
func (r *mutationResolver) CreateMeetup(ctx context.Context, input model.NewMeetup) (*model.Meetup, error) {
	if len(input.Name) < 3 {
		return nil, errors.New("name not long enough")
	}

	if len(input.Description) < 3 {
		return nil, errors.New("description not long enough")
	}

	meetup := &model.Meetup{
		Name:        input.Name,
		Description: input.Description,
		UserID:      4,
	}

	return r.MeetupsRepo.CreateMeetup(meetup)
}

// UpdateMeetup is the resolver for the updateMeetup field.
func (r *mutationResolver) UpdateMeetup(ctx context.Context, id string, input model.UpdateMeetup) (*model.Meetup, error) {
	idConverted, _ := strconv.Atoi(id)

	if idConverted <= 0 {
		return nil, errors.New("invalid id")
	}

	meetup, err := r.MeetupsRepo.GetMeetupByID(idConverted)

	if err != nil {
		return nil, err
	}

	if meetup == nil || meetup.ID == 0 {
		return nil, errors.New("meetup not exist")
	}

	didUpdate := false

	if input.Name != nil {
		if len(*input.Name) < 3 {
			return nil, errors.New("name not long enough")
		}
		meetup.Name = *input.Name
		didUpdate = true
	}

	if input.Description != nil {
		if len(*input.Description) < 3 {
			return nil, errors.New("description not long enough")
		}
		meetup.Description = *input.Description
		didUpdate = true
	}

	if !didUpdate {
		return nil, errors.New("no update done")
	}

	meetup, err = r.MeetupsRepo.UpdateMeetup(meetup)
	if err != nil {
		return nil, fmt.Errorf("error when updating meetup: %+v", err)
	}

	return meetup, nil
}

// DeleteMeetup is the resolver for the deleteMeetup field.
func (r *mutationResolver) DeleteMeetup(ctx context.Context, id string) (bool, error) {
	idConverted, _ := strconv.Atoi(id)

	if idConverted <= 0 {
		return false, errors.New("invalid id")
	}

	meetup, err := r.MeetupsRepo.GetMeetupByID(idConverted)

	if err != nil {
		return false, err
	}

	if meetup == nil || meetup.ID == 0 {
		return false, errors.New("meetup not exist")
	}

	err = r.MeetupsRepo.DeleteMeetup(meetup)
	if err != nil {
		return false, fmt.Errorf("error when deleting meetup: %+v", err)
	}

	return true, nil
}

// Meetups is the resolver for the meetups field.
func (r *queryResolver) Meetups(ctx context.Context) ([]*model.Meetup, error) {
	return r.MeetupsRepo.GetMeetups()
}

// Meetup is the resolver for the meetup field.
func (r *queryResolver) Meetup(ctx context.Context, id string) (*model.Meetup, error) {
	idConverted, _ := strconv.Atoi(id)
	if idConverted <= 0 {
		return nil, errors.New("invalid id")
	}

	return r.MeetupsRepo.GetMeetupByID(idConverted)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return r.UsersRepo.GetUsers()
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	idConverted, _ := strconv.Atoi(id)
	if idConverted <= 0 {
		return nil, errors.New("invalid id")
	}

	return r.UsersRepo.GetUserByID(idConverted)
}

// Meetups is the resolver for the meetups field.
func (r *userResolver) Meetups(ctx context.Context, obj *model.User) ([]*model.Meetup, error) {
	return r.MeetupsRepo.GetMeetupsByUserID(obj.ID)
}

// Meetup returns MeetupResolver implementation.
func (r *Resolver) Meetup() MeetupResolver { return &meetupResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type meetupResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
